### ISSUE TITLE
home limit

### ISSUE THREAD

**Issue by waaaac** [Homes-MinecraftServerMod/Homes#11]
game 1.12
plug 0.9.0
When limit is set to -1, normal player can set any amount of homes
When limit is set to -2 or any number higher, normal player cannot have more than default home
I uninstalled all other plugins and test each scenario, but cannot get only 2 homes per player limit.

**Comment by MasahiroSaito** [comment]
@waaaac Thank you for reporting! This is a bug, so fix it in version 0.9.1.
