### ISSUE TITLE
homes.general ?

### ISSUE THREAD

**Issue by bentoweb** [Homes-MinecraftServerMod/Homes#3]
Hello !
When I try a command line, i get an error.
Set permission "homes.general" ? Okay ? Where ? How ? :/

**Comment by bentoweb** [comment]
And "/home myhome" does not work. This teleport to unamed home

**Comment by MasahiroSaito** [comment]
Write Permission in the permissions.yml of the server, or install PermissionEx and make the setting.

> - [[Bukkit guide] Permissions](https://bukkit.org/threads/bukkit-guide-permissions.50305/)
> - [PermissionsEx](https://dev.bukkit.org/projects/permissionsex)

Information of Homes permissions is [here](https://github.com/MasahiroSaito/Homes/wiki/Permissions)

**Comment by bentoweb** [comment]
Thanks !!
