### ISSUE TITLE
home limits

### ISSUE THREAD

**Issue by waaaac** [Homes-MinecraftServerMod/Homes#4]
game v-1.12 
home limit does not stop general player from making more homes than the set limit

**Comment by MasahiroSaito** [comment]
@waaaac Thank you, waaaac! I will investigate the problem.

**Comment by MasahiroSaito** [comment]
Release 0.9.0 for Spigot and Bukkit ver 1.12 1.10 1.11
https://dev.bukkit.org/projects/homes-teleportation-plugin/files/2435588
